Migrate from nextjs page to app router (#4087)
* small changes and migrate to app router

* fix graphql route

* refactor: extract out some providers

* fix: lint errors, ts errors, minor reformatting

* fix: lint errors, ts errors, minor reformatting

* fix nextjs / RSC problem:

Error occurred prerendering page "/privacy". Read more: https://nextjs.org/docs/messages/prerender-error
RangeError: Maximum call stack size exceeded
    at ignore-listed frames {
  digest: '1136043147'
}

* remove obsolete debug message

* fix: minor codacy warning && cosmetics

* fix: minor change in next-env file

* fix: suppress hydration warning (investigate later if still needed)

* fix: error about li in li dom element

* fix: empty board page because of params is Promise since next 16

* optimise types, by next typegen ...

* next typegen did not add /sign-in page as valid route

* ignore cypress fails on webpage error

* fix order of clear cache/signout

* minor adoptions, revert unwanted changes